spring.application.name=bff

server.port=8443
video-service.url=http://54.160.143.160:8080
manga-service.url=http://54.85.21.149:8282

server.ssl.key-store=classpath:ssl/springboot.jks
server.ssl.key-store-password=123456
server.ssl.key-store-type=JKS
server.ssl.key-alias=springboot
